/**
 * Electrode Native generic navigation api (V2.0)
 * Navigation helper
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import ENNavigationRequests  from '../../src/api/ENNavigationRequests';

describe('ENNavigationApi', function(){
  let requests;
  beforeEach(function() {
    requests = new ENNavigationRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('navigate', function() {
      it('should send request navigate successfully', ()=> {
        //uncomment below and update the code to test navigate
        //return requests.navigate(route: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
